### ISSUE TITLE
concatenation

### ISSUE THREAD

**Issue by HUBBA-ER** [HUBBA-ER/HUBBA-ER.github.io#1]
Is concat like this valid in JS?

**Comment by tripplyons** [comment]
Your code is valid, except for the fact that you don't have semicolons at the end of the lines.

**Comment by HUBBA-ER** [comment]
good. btw did you know that every hour on github over 780, 000 bytes of data are sent and shared through issues, collab and gists.

**Comment by HUBBA-ER** [comment]
can you please do a run check?

**Comment by HUBBA-ER** [comment]
I will add a credits and else op too

**Comment by HUBBA-ER** [comment]
melike.

**Comment by HUBBA-ER** [comment]
#I AM AMAZING

**Comment by HUBBA-ER** [comment]
I am a troller!

**Comment by HUBBA-ER** [comment]
# #_LOLOLOLOLOLOLOLOLOLOLOLOLOL_

I am amazing!

**Comment by tripplyons** [comment]
@HUBBA-ER is a **real** troller!

**Comment by HUBBA-ER** [comment]
@tripplyons is a _real_ hacker

**Comment by HUBBA-ER** [comment]
# #LOLOLOLOLOL

i am cool

**Comment by tripplyons** [comment]
#LOLOLOL!!!!

**Comment by tripplyons** [comment]
# LOL

**LLLOOOLLL**

**Comment by tripplyons** [comment]
Check out a game I made: [http://tripplyons.github.io/puzzles/two.html](http://tripplyons.github.io/puzzles/two.html)

**Comment by HUBBA-ER** [comment]
# yoloswag

**Comment by HUBBA-ER** [comment]
_beulah_

**Comment by tripplyons** [comment]
I'm in coding club!

**Comment by HUBBA-ER** [comment]
# Hi
